/**
 * Alle deutschen UI-Strings zentral — der Tisch-Jargon (deutsche Labels,
 * englische Regelbegriffe wie in der Gruppen-Excel) ist hier einstellbar.
 */
export const S = {
  appName: "Chardex35",

  nav: {
    characters: "Charaktere",
    compendium: "Kompendium",
    dice: "Würfel",
    settings: "Einstellungen",
  },

  abilities: {
    str: "ST",
    dex: "GE",
    con: "KO",
    int: "IN",
    wis: "WE",
    cha: "CH",
  } as Record<string, string>,
  abilityNames: {
    str: "Stärke",
    dex: "Geschicklichkeit",
    con: "Konstitution",
    int: "Intelligenz",
    wis: "Weisheit",
    cha: "Charisma",
  } as Record<string, string>,

  saves: { fort: "Fortitude", ref: "Reflex", will: "Will" } as Record<string, string>,

  sheet: {
    tabs: {
      stats: "Werte",
      combat: "Kampf",
      skills: "Fertigkeiten",
      spells: "Zauber",
      inventory: "Ausrüstung",
      feats: "Talente",
      notes: "Notizen",
    },
    hp: "TP",
    hpMax: "max.",
    damage: "Schaden",
    nonlethal: "Nichttödlich",
    temp: "Temp. TP",
    ac: "RK",
    touch: "Berührung",
    flatFooted: "Auf dem falschen Fuß",
    init: "Initiative",
    speed: "Bewegung",
    bab: "GAB",
    grapple: "Ringkampf",
    level: "Stufe",
    xp: "EP",
    nextLevel: "nächste Stufe",
    attacks: "Angriffe",
    damage2: "Schaden",
    critical: "Krit.",
    ranks: "Ränge",
    maxRanks: "max.",
    classSkill: "Klassenfertigkeit",
    conditions: "Zustände",
    features: "Klassenfähigkeiten",
    miscMods: "Sonstige Modifikatoren",
    encumbrance: { light: "Leichte Last", medium: "Mittlere Last", heavy: "Schwere Last", overloaded: "Überladen!" } as Record<string, string>,
    slots: "Slots",
    dcBase: "SG-Basis",
    casterLevel: "Zauberstufe",
    breakdownSuppressed: "wirkt nicht",
    portrait: "Porträt",
  },

  actions: {
    create: "Anlegen",
    save: "Speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    edit: "Bearbeiten",
    add: "Hinzufügen",
    remove: "Entfernen",
    back: "Zurück",
    next: "Weiter",
    done: "Fertig",
    roll: "Würfeln",
    export: "Exportieren",
    import: "Importieren",
    search: "Suchen…",
    equip: "Anlegen",
    unequip: "Ablegen",
    levelUp: "Stufenaufstieg",
  },

  wizard: {
    title: "Neuer Charakter",
    steps: ["Volk", "Attribute", "Klasse", "Fertigkeiten", "Talente", "Ausrüstung", "Fertig"],
    name: "Name",
    playerName: "Spieler:in",
    hpRoll: "TP-Wurf",
    pointsLeft: "Punkte übrig",
    slotsLeft: "Slots übrig",
  },

  settings: {
    houseRules: "Hausregeln",
    fractional: "Fraktionale BAB/Saves (Unearthed Arcana)",
    maxHpL1: "Volle TP auf Stufe 1",
    xpPenalty: "Multiclass-EP-Strafe (RAW)",
    exportTitle: "Export / Import",
    exportAll: "Alles exportieren (JSON)",
    importFile: "JSON importieren",
    storage: "Speicher",
    persisted: "Speicher ist persistent",
    notPersisted: "Speicher NICHT garantiert persistent — Export als Backup empfohlen!",
    license: "Lizenz (OGL)",
    dataPrivacy:
      "Alle Daten liegen nur lokal auf diesem Gerät (IndexedDB). Teilen per Export/Import.",
  },

  compendium: {
    kinds: {
      race: "Völker",
      class: "Klassen",
      feat: "Talente",
      skill: "Fertigkeiten",
      spell: "Zauber",
      item: "Gegenstände",
      monster: "Monster",
      condition: "Zustände",
      spelllist: "Zauberlisten",
    } as Record<string, string>,
    sourceSrd: "SRD",
    sourceHomebrew: "Homebrew",
    empty: "Nichts gefunden.",
  },

  dice: {
    title: "Würfel",
    history: "Verlauf",
    placeholder: "z.B. 2d6+3",
    invalid: "Ungültiger Ausdruck",
  },

  spells: {
    prepared: "Vorbereitet",
    known: "Bekannt",
    spellbook: "Zauberbuch",
    prepare: "Vorbereiten",
    learn: "Lernen",
    cast: "Wirken",
    rest: "Rast (Slots zurücksetzen)",
    browse: "Zauberliste durchsuchen",
    onlySpellbook: "nur Zauberbuch",
    level: "Grad",
    dc: "SG",
    noSlotsLeft: "keine Slots mehr",
    preparedHint:
      "Wirken zählt die Slots des Grads hoch — welcher konkrete Zauber verbraucht ist, merkt ihr euch wie am Tisch üblich.",
    knownLimit: (have: number, max: string) => `${have}/${max} bekannt`,
  },

  levelUp: {
    title: "Stufenaufstieg",
    ready: "⬆ Bereit zum Aufstieg!",
    chooseClass: "Klasse für die neue Stufe",
    hpRoll: "TP-Wurf für diese Stufe",
    rollHp: "würfeln",
    abilityIncrease: "Attributssteigerung (alle 4 Stufen)",
    skills: "Fertigkeitspunkte verteilen",
    feats: "Neues Talent wählen",
    newSpells: "Neue Zauber lernen",
    summary: "Zusammenfassung",
    apply: "Stufe aufsteigen",
    hpDelta: "Trefferpunkte",
    newLevel: "Neue Stufe",
  },

  misc: {
    loading: "Lade…",
    seedRunning: "SRD-Kompendium wird eingerichtet…",
    noCharacters: "Noch keine Charaktere. Leg deinen ersten an!",
    confirmDelete: (name: string) => `„${name}" wirklich löschen?`,
    issues: "Hinweise",
    updateAvailable: "Update verfügbar — neu laden?",
    offlineReady: "App ist offline verfügbar.",
  },
};
